### ISSUE TITLE
use webpack  and after build, has error

### ISSUE THREAD

**Issue by lgoldfish** [skmdev/koa-decorator-ts#18]
`
> node ./build/app.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/Users/jinyu/Workspace/afe-acl-service/build/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
`

**Comment by richarddd** [comment]
I can't find the relevance in this so closing it
